(* 12 星座を示す型 *)
type seiza_t = Ohitsujiza   (* ♈️ *)
             | Oushiza      (* ♉️ *)
             | Futagoza     (* ♊️ *)       
             | Kaniza       (* ♋️ *)
             | Shishiza     (* ♌️ *)
             | Otomeza      (* ♍️ *)
             | Tenbinza     (* ♎️ *)
             | Sasoriza     (* ♏️ *)
             | Iteza        (* ♐️ *)
             | Yagiza       (* ♑️ *)
             | Mizugameza   (* ♒️ *)